name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Adjust to your .NET version

      - name: Install Dependencies
        run: dotnet restore

      - name: Run Tests with Coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/

      - name: Publish Coverage Report
        run: |
          mkdir -p coverage
          mv TestResults/*/coverage.cobertura.xml coverage/ || echo "No coverage file found"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Extract Coverage Percentage
        run: |
         if [[ ! -f coverage/coverage.opencover.xml ]]; then
         echo "Error: coverage.opencover.xml not found."
         exit 1
         fi
         COVERAGE=$(grep -oP '(?<=line-rate=")[0-9.]+(?=")' coverage/coverage.opencover.xml)
         if [[ -z "$COVERAGE" ]]; then
         echo "Error: Coverage value not found in coverage.opencover.xml."
         exit 1
         fi
         PERCENTAGE=$(echo "$COVERAGE * 100" | bc)
         echo "Coverage: $PERCENTAGE%"
         echo "coverage=$PERCENTAGE" >> $GITHUB_ENV

      - name: Update README with Coverage Badge
        run: |
         if [[ -z "${{ env.coverage }}" || ! "${{ env.coverage }}" =~ ^[0-9]+$ ]]; then
         echo "Error: Invalid coverage value '${{ env.coverage }}'. Cannot update README.md."
         exit 1
         fi
         BADGE_URL="https://img.shields.io/badge/coverage-${{ env.coverage }}%25-brightgreen"
         if grep -q "coverage-" README.md; then
         echo "Existing coverage badge found. Replacing with new badge."
         sed -i "s|https://img.shields.io/badge/coverage-[0-9]*%25-brightgreen|$BADGE_URL|" README.md
         else
         echo "No existing coverage badge found. Adding one to README.md."
         echo "![Coverage]($BADGE_URL)" >> README.md
         fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update coverage badge to ${{ env.coverage }}%"
          git push

