name: .NET Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies (PO.Test only)
        run: dotnet restore ./PO.Test

      - name: Build test project
        run: dotnet build ./PO.Test --no-restore

      - name: Run tests with detailed output
        run: dotnet test ./PO.Test --no-build --logger:"console;verbosity=detailed"
